# Generated by Django 5.2.14 on 2026-06-11 09:36

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_uploadedfile_notechunk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notechunk',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='note_chunk_vector_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
